### ISSUE TITLE
No detections generated by Falcon Sensor on GCP GKE + Container Optimized OS

### ISSUE THREAD

**Issue by mj-sakellaropoulos** [CrowdStrike/falcon-operator#256]
Hi

I have been trying for a while to get falcon-operator running in Sidecar mode for Container Optimzed OS in a test GKE cluster. I have installed via `kubectl apply -f https://raw.githubusercontent.com/CrowdStrike/falcon-operator/main/deploy/falcon-operator.yaml`. I have deployed the FalconContainer using both the crowdstrike registry and gcr registry (both are working and running the injector).
For the GCR method, I have manually created the service account and secret as per the docs.

However, using the test detections (via bash attached to pod container), nothing is generated. The host shows as "Online" in the Falcon UI. Realtime response hangs when trying to connect to the pod.

We also have an active support case on this topic. I have spoken with one of your engineers on Zoom and I was recommeded to use GCR instead of your registry, and to follow the [E2E Guide](https://github.com/CrowdStrike/falcon-operator/blob/main/docs/deployment/gke/README.md), which I did try with no success. (I would also like to avoid the OLM)

How can I go about troubleshhoting/resolving this?

### Specs and logs

FalconContainer:
```
apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconContainer
metadata:
  name: falcon-container-experimental
spec:
  falcon_api:
    client_id: redacted
    client_secret: redacted
    cloud_region: autodiscover
  registry:
    type: gcr #also tried crowdstrike here, same result
  installer_args:
    - '-falconctl-opts'
    - '--provisioning-token=redacted --tags=k8s-experiment'
```

Injector Logs:
```
time="2022-06-10T14:47:12Z" level=info msg="Starting Injector..."
time="2022-06-10T14:47:12Z" level=info msg="Starting HTTPS server" listen port=4433
time="2022-06-10T14:47:43Z" level=info msg="Handling webhook request" id=fdfa3600-d286-441b-add4-dc83889abc9c namespace=default
time="2022-06-10T14:47:43Z" level=info msg="Found registry" image="debian:stable-slim" namespace=default podName=debian registry=docker.io
time="2022-06-10T14:47:43Z" level=info msg="Updating container spec" containerName=debian containerNumber=1/1 namespace=default podName=debian
time="2022-06-10T14:47:43Z" level=warning msg="Falcon-sensor will run as root because of mismatch in runAsUser for containers" containerName=debian
time="2022-06-10T14:47:43Z" level=info msg="Successfully handled webhook request" id=fdfa3600-d286-441b-add4-dc83889abc9c namespace=default
```

Example pod spec used:
```
apiVersion: v1
kind: Pod
metadata:
  name: debian
spec:
  containers:
  - name: debian
    image: debian:stable-slim
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10s;done"]
```

### Versions
Sensor: "latest" `6.41.0-2402.container.x86_64.Release.US-2`
Kubernetes: `1.22.8-gke.201`
Container Optimized OS: `1.22.8-gke.201`
