### ISSUE TITLE
Deleting cloudformation template does not remove node sensors

### ISSUE THREAD

**Issue by jhseceng** [CrowdStrike/falcon-operator#293]
Deleting a CFT that uses the extension will delete the operator but does not delete the node sensors
```
[ec2-user@ip-10-0-151-108 ~]$ kubectl get pods -A
NAMESPACE         NAME                                                 READY   STATUS        RESTARTS   AGE
default           webapp-6b9df8788c-46n55                              1/1     Running       0          8h
falcon-operator   falcon-operator-controller-manager-64b9f7c89-ddvp9   0/1     Terminating   0          9h
falcon-system     falcon-node-sensor-45mv4                             1/1     Running       0          6m27s
falcon-system     falcon-node-sensor-9fb47                             1/1     Running       0          6m27s
kube-system       aws-load-balancer-controller-d94dd9fdd-55s6f         1/1     Running       0          8h
kube-system       aws-node-b66kb                                       1/1     Running       0          9h
kube-system       aws-node-n5jvq                                       1/1     Running       0          9h
kube-system       coredns-85d5b4454c-d94ht                             1/1     Running       0          9h
kube-system       coredns-85d5b4454c-frxgs                             1/1     Running       0          9h
kube-system       kube-proxy-bnbqn                                     1/1     Running       0          9h
kube-system       kube-proxy-l8qqs                                     1/1     Running       0          9h
[ec2-user@ip-10-0-151-108 ~]$ kubectl get pods -A
NAMESPACE       NAME                                           READY   STATUS    RESTARTS   AGE
default         webapp-6b9df8788c-46n55                        1/1     Running   0          8h
falcon-system   falcon-node-sensor-45mv4                       1/1     Running   0          6m34s
falcon-system   falcon-node-sensor-9fb47                       1/1     Running   0          6m34s
kube-system     aws-load-balancer-controller-d94dd9fdd-55s6f   1/1     Running   0          8h
kube-system     aws-node-b66kb                                 1/1     Running   0          9h
kube-system     aws-node-n5jvq                                 1/1     Running   0          9h
kube-system     coredns-85d5b4454c-d94ht                       1/1     Running   0          9h
kube-system     coredns-85d5b4454c-frxgs                       1/1     Running   0          9h
kube-system     kube-proxy-bnbqn                               1/1     Running   0          9h
kube-system     kube-proxy-l8qqs                               1/1     Running   0          9h



AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy falcon-operator using CloudFormation to existing EKS cluster"
Metadata:
  cfn-lint: { config: { ignore_checks: [W9002, W9003, W9004, W9006, E9007, E9008] } }
Parameters:
  PermissionsBoundary:
    Type: String
    Default: ''
  EksClusterName:
    Type: String
  FalconSensorType:
    AllowedValues:
      - FalconContainer
      - FalconNodeSensor
    Default: FalconNodeSensor
    Type: String
  FalconClientID:
    Description: Falcon Client ID
    Type: String
  FalconClientSecret:
    Description: Falcon Client Secret
    Type: String
Conditions:
  PermissionsBoundary: !Not [ !Equals [ !Ref PermissionsBoundary, '' ] ]
  WantsContainer: !Equals [!Ref FalconSensorType, 'FalconContainer']
  WantsNodeSensor: !Equals [!Ref FalconSensorType, 'FalconNodeSensor']
Resources:
  InstallOperator:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: falcon-operator
      Url: https://raw.githubusercontent.com/CrowdStrike/falcon-operator/main/deploy/falcon-operator.yaml
  InstallFalconContainer:
    Type: "AWSQS::Kubernetes::Resource"
    Condition: WantsContainer
    DependsOn: InstallOperator
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: falcon-operator
      Manifest: !Sub |
        apiVersion: falcon.crowdstrike.com/v1alpha1
        kind: ${FalconSensorType}
        metadata:
          name: default
        spec:
          falcon_api:
            client_id: ${FalconClientID}
            client_secret: ${FalconClientSecret}
            cloud_region: autodiscover
          registry:
            type: crowdstrike
          falcon:
            tags: 
              - ${GroupingTag}
  InstallFalconNodeSensor:
    Type: "AWSQS::Kubernetes::Resource"
    Condition: WantsNodeSensor
    DependsOn: InstallOperator
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: falcon-operator
      Manifest: !Sub |
        apiVersion: falcon.crowdstrike.com/v1alpha1
        kind: ${FalconSensorType}
        metadata:
          name: falcon-node-sensor
        spec:
          falcon_api:
            client_id: ${FalconClientID}
            client_secret: ${FalconClientSecret}
            cloud_region: autodiscover
          node: {}
          falcon: {}
```
