### ISSUE TITLE
Add new OpenShift feature annotations to CSV

### ISSUE THREAD

**Issue by evanstoner** [CrowdStrike/falcon-operator#498]
These will be required for new operator releases starting March 1.

```yaml
metadata:
    annotations:
        features.operators.openshift.io/disconnected: "true"
        features.operators.openshift.io/fips-compliant: "true"
        features.operators.openshift.io/proxy-aware: "true"
        features.operators.openshift.io/tls-profiles: "true"
        features.operators.openshift.io/token-auth-aws: "true"
        features.operators.openshift.io/token-auth-azure: "false"
        features.operators.openshift.io/token-auth-gcp: "false"
        features.operators.openshift.io/cnf: "false"
        features.operators.openshift.io/cni: "false"
        features.operators.openshift.io/csi: "false"
```

KB for partners: https://access.redhat.com/articles/7056408

Annotation definitions: https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs
