### ISSUE TITLE
spec:   falcon:     tags: 'test-cluster,dev' section seems to be throw an error

### ISSUE THREAD

**Issue by devjpc** [CrowdStrike/falcon-operator#526]
The 
```
spec:
  falcon:
    tags: 'test-cluster,dev'
```
section of 

```
apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconContainer
metadata:
  name: falcon-sidecar-sensor
spec:
  falcon:
    tags: 'test-cluster,dev'
  falcon_api:
    client_id: PLEASE_FILL_IN
    client_secret: PLEASE_FILL_IN
    cloud_region: autodiscover
  registry:
    type: crowdstrike
```
seems to throw this error - `spec.falcon.tags: Invalid value: "string": spec.falcon.tags in body must be of type array: "string"`

@musayev-io
