### ISSUE TITLE
[Feature Request] Support secret references in CRDs

### ISSUE THREAD

**Issue by IronMage** [CrowdStrike/falcon-operator#655]
## Problem Statement
Storing secret values in the CRDs installed by the Falcon Operator makes supporting sensor definitions in GitOps impossible; since the containing resource is a CRD, tools like `SealedSecrets` can't be used to protect them in git.

Additionally, these CRDs are not treated as sensitive by Kubernetes and therefore do not get the same built-in protections that secrets do (e.g. `ectd` encryption at rest).

## Solution
Support secret references in CRDs that require secret values (e.g. `client_secret`).

### Example
```yaml
kind: FalconNodeSensor
apiVersion: falcon.crowdstrike.com/v1alpha1
metadata:
  name: example
spec:
  falcon_api:
    client_secret_ref:
      name: example-secret
```
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
stringData:
  client_id: abc123
  client_secret: mysecretvalue
  cloud_region:  myregion
```
