### ISSUE TITLE
deploy falcon operator on multi-arch

### ISSUE THREAD

**Issue by bsamsom** [CrowdStrike/falcon-operator#668]
Were deploying falcon into a multi-arch cluster, and support was finally added for that in 1.6.0 but no examples of how to configure it.

the notes in the read me are:
> Falcon KAC will have multi-arch images starting with version `7.26.x`. Operator versions <= 1.3.x are still compatible with Falcon KAC v7.26+, but Falcon KAC will only be deployed to ARM64 clusters if it is configured with the new node affinity option added in Operator version `1.6.x`.
> Multi architecture images will not automatically deploy to ARM64 clusters, without updating `admissionConfig.nodeAffinity`.

we deploy FalconNodeSensor as:
```
apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconNodeSensor
metadata:
  name: falcon-node-sensor
spec:
  falcon_api: 
    client_id: PLEASE_FILL_IN
    client_secret: PLEASE_FILL_IN
    cloud_region: autodiscover
  falcon: {}
```
and
``` FalconAdmission as:
apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconAdmission
metadata:
  name: falcon-admission
spec:
  falcon_api: 
    client_id: PLEASE_FILL_IN
    client_secret: PLEASE_FILL_IN
    cloud_region: autodiscover
  registry:
    type: crowdstrike
  admissionConfig:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - arm64
            - amd64
```

when looking in the cluster we see:
```
kubectl get falconadmission 
NAME               OPERATOR VERSION   FALCON SENSOR
falcon-admission   1.6.0              7.26.0-2404.Release.US-1
```
and
```
kubectl get falconnodesensors
NAME                 OPERATOR VERSION   FALCON SENSOR
falcon-node-sensor   1.6.0              7.14.0-16703-1.falcon-linux.x86_64.Release.US-1
```

but the arm nodes are still getting the 7.14.0-16703-1.falcon-linux.x86_64.Release.US-1 image instead of the multi-arch image.

@mr-jungchoi  as you updated those docs and had the [commit](https://github.com/CrowdStrike/falcon-operator/pull/651) for adding in multi-arch, can you please let me know what im doing wrong or provide an example configuration for deploying multi-arch images.
